### ISSUE TITLE
[Question] Media Player Additional Features?

### ISSUE THREAD

**Issue by uvjim** [unfoldedcircle/core-api#32]
When using a media player entity to represent a set-top-box, how is it best to facilitate the number buttons, record and recorded shows buttons?  The set-top-box (TiVo) I use also has a "Thumbs Up" and "Thumbs Down" functionality, how could these also be represented?

## Expected Behavior or Design

I would expect the CHANNEL_SWITCHER to also include number buttons.

## Current Behavior or Design

Currently the feature for CHANNEL_SWITCHER does not facilitate number buttons that would be used for changing channels.  I also cannot see a feature that would imply the ability to record.

## Possible Solution

I guess the options I'm after could be provided as additional `Button` entities that are associated with the same `entity_id`.  However, this could overwhelm the UI or become cumbersome.

One option would be to provide additional features: -

1. `NUMBER_BUTTONS` - this would be responsible for the number commands for a media player
2. `DVR` - this would be responsible for providing functionality for "Record" and "My Recordings"
3. `FAVOURITES` - to expose a `like` and `dislike` option to mimic the thumbs up and down

**Comment by zehnm** [comment]
Additional commands in the media-player entities are currently not supported, but it's a planned feature. Either as "custom commands", or providing a separate "remote-entity".

**Comment by zehnm** [comment]
Specification of additional commands in the media-player has started in branch `feat/media-player_commands`.
Diff: https://github.com/unfoldedcircle/core-api/compare/main...feat/media-player_commands
