### ISSUE TITLE
Missing hostname or device ID in APIs

### ISSUE THREAD

**Issue by albaintor** [unfoldedcircle/core-api#33]
Actually while using mdns discovery you can get the hostname of the remote as a unique ID in the format RemoteTwo-<mac address>.local

But there this info cannot be retrieved using APIs

The use case is the following : adding the remote two to Home assistant (not the HA integration driver, but add the RC2 to home assistant to control it from HA)

1. Detect devices through mdns
2. User can select one of them or if not detected properly he will submit the IP address or hostname directly
3. The integration will store the new device information BUT will check before if the device does not already exist 
**=> problem we don't have any available device ID (serial number, hostname or mac address) to distinguish devices

The hostname and/or serial number and/or mac address should be added to remote API /pub/version of /pub/* to avoid unnecessary authentication

Thank you

**Comment by zehnm** [comment]
The user configurable name is returned in the open `GET /api/pub/version` endpoint. If there are multiple remotes in a household, they should have different names ;-)
The system information can be retrieved with `GET /api/system` and includes the serial number.

Do I understand you correctly, that you'd like to have a unique device identifier in a public endpoint?

**Comment by zehnm** [comment]
Enhancing the public endpoint with a unique identifier makes sense and I can add it in the next release. Hostname and MAC address are probably the best options.
Adding device specific information to zeroconf will take more effort (it's currently a static service file generated at build time, placed on a read-only filesystem, and the hostname is the only supported placehoder).

**Comment by albaintor** [comment]
Great thank you

**Comment by zehnm** [comment]
Hostname and MAC address are added to the version info object. A new firmware is expected to be released next week.

**Comment by albaintor** [comment]
Great thank you and keep on the hard work
